### ISSUE TITLE
Questions regarding the animation function

### ISSUE THREAD

**Issue by rwang0417** [Ro3code/aircraft_3d_animation#1]
Dear Rodney,

Thanks a lot for creating this interesting project. I followed the steps in your post on Medium and successfully ran the animation. It looks amazing! Before I could run it, the 'Model3D.Control(j).rot_offset_deg' variable used in `aircraft_3d_animation.m` line 292 gave me an error. It seems that this variable doesn't appear anywhere else in the project. Could you please give me some hints on what I missed here? Any help would be appreciated!

PS: I also had to comment out from line 192 in `import_std_model.m` and manually matched the mat model name before running the code.

Best regards,
Ran

**Comment by Ro3code** [comment]
Hi Ran,

Thanks for your kind comments. You are completely right! I forgot to remove that feature from the official release. The `rot_offset_deg` variable was ment to provide a deflection angle bias for the flight control surfaces. For example, in my local version of this tool, I have a 3D Eurofighter implemented and the foreplane/canard surface has a 6deg bias for 0cmd deflection.

Regarding the `import_stl_model.m` I also corrected the tranformation group handles initialization.

Thank you once again for reporting these issues. I hope you have found the tool useful for your application.

All the best,
Rodney
