### ISSUE TITLE
Flight Dynamics Model

### ISSUE THREAD

**Issue by peterdsharpe** [Ro3code/aircraft_3d_animation#2]
Hi there,

Thanks for open-sourcing this code and your [accompanying article](https://medium.com/codestory/3d-animations-made-simple-with-matlab-visualizing-flight-test-data-and-simulation-results-ed399cdcc711) - this was a really interesting read!

I may be missing it, but it looks like the flight dynamics model isn't included in this repository (all I can find are example time histories in the `/examples/` directory). Do you know where one could find a software copy of the ADMIRE flight dynamics model?

Thanks!

**Comment by Ro3code** [comment]
Hi Peter,

You are right, this is just a visualization tool, the flight dynamics simulation environment is not provided in this repo. Indeed the ADMIRE model has been recently discontinued. I can send it to you via email if you want.

Rodney

**Comment by peterdsharpe** [comment]
Hi there - this is so kind of you! I'd really love to explore that model - could you please email me at pds@mit.edu?

Thanks!

**Comment by peterdsharpe** [comment]
Hi @Ro3code - just wanted to bump this issue! Thanks!

**Comment by rwang0417** [comment]
Hi Rodney, I also got a 404 on the ADMIRE download website. May I trouble you to email me a copy of the ADMIRE model as well? My email is rwang0417@tamu.edu. Many thanks!
